/* eslint-disable no-await-in-loop */
import { toMatchImageSnapshot } from 'jest-image-snapshot';
import { getEmail } from './email';

const path = require('path');
const fs = require('fs');

expect.extend({ toMatchImageSnapshot });

const sitePath = process.env.TIG_ADDRESS || 'http://host.docker.internal:5003';

/**
 * Takes a screen snapshot.
 * Either creates a file name and adds the screenshot and filname to a
 * snapshots array, or tests expect toMatchImageSnapshot.
 *
 * The filename is 'fileNamePrefix + index' where index is either auto
 * generated by incrementing the last snapshot in the snapshots array
 * (assuming the file name prefixes are the same), or is defined from
 * startIndex, or defaults to 0.
 *
 * @param {Array<Array<string, image>>\|null} snapshots - Existing snapshots to
 *                                    add new snapshot to, or if null, will do
 *                                    a expect toMatchImageSnapshot on it
 * @param {string} [fileNamePrefix] - File name before the snapshot count
 * @param {(number\|null)} [startIndex] - Snapshot number to use, null for auto
 *
 */
async function snap(
  fileNamePrefix = '', snapshots = null, startIndex = null,
  threshold = 3, screenshotOptions = {},
) {
  let index = 0;
  // Calculate index
  if (startIndex == null && snapshots != null) {
    if (snapshots.length > 0) {
      const lastPrefix =
        snapshots.slice(-1)[0][0].replace(/-[0-9]*$/, '');
      const lastIndex =
        snapshots.slice(-1)[0][0].replace(/.*-([0-9]*)$/, '$1');
      if (lastPrefix === fileNamePrefix) {
        index = parseInt(lastIndex, 10) + 1;
      }
    }
  }
  if (startIndex != null) {
    index = startIndex;
  }
  const screenshot = await page.screenshot(screenshotOptions);
  let fileName = `${fileNamePrefix}-${index.toString(10).padStart(2, '0')}`;
  if (startIndex === -1) {
    fileName = fileNamePrefix;
  }
  if (snapshots == null) {
    expect(screenshot).toMatchImageSnapshot({
      customSnapshotIdentifier: fileName,
      failureThreshold: threshold,
    });
  } else {
    snapshots.push([fileName, screenshot, threshold]);
  }
}

async function debugSnapshot(
  fileNamePrefix, snapshots = null, startIndex = null,
) {
  if (fileNamePrefix) {
    await snap(fileNamePrefix, snapshots, startIndex);
  }
}

function checkSnap(index, snapshots, replacements) {
  const [fileName, screenshot, threshold] = snapshots[index];
  replacements.push(snapshots[index]);
  expect(screenshot).toMatchImageSnapshot({
    customSnapshotIdentifier: fileName,
    failureThreshold: threshold,
  });
  replacements.pop();
}

function sleep(ms) {
  return new Promise(resolve => setTimeout(resolve, ms));
}

async function goHome(width = 0, height = 0) {
  await page.goto(sitePath);

  if (width !== 0 && height !== 0) {
    await page.setViewport({ width, height });
  }
}

async function snapshot(fileName) {
  const image = await page.screenshot();
  expect(image).toMatchImageSnapshot({
    customSnapshotIdentifier: fileName,
  });
}

async function getToken(prefix, oldMsgNumber) {
  await sleep(2000);
  let [msgNumber, body] = await getEmail();
  let count = 0;
  while (msgNumber === oldMsgNumber && count < 5) {
    await sleep(2000);
    [msgNumber, body] = await getEmail();
    count += 1;
  }
  expect(msgNumber).not.toEqual(oldMsgNumber);
  const [token] = body.match(new RegExp(`${prefix}/[^\r]*`));

  return token;
}

async function setFormInput(id, text) {
  await page.evaluate((idStr) => {
    document.getElementById(idStr).value = '';
  }, id);
  await page.type(`#${id}`, text);
}

async function click(id) {
  await Promise.all([
    page.waitForNavigation(),
    // page.click(`#${id}`),
    page.$eval(`#${id}`, elem => elem.click()),
  ]);
}

async function getLatestMessage() {
  const email = await getEmail();
  return email[0];
}


async function login(
  username, password,
  fileNamePrefix = '', snapshots = null, startIndex = null,
) {
  await debugSnapshot(fileNamePrefix, snapshots, startIndex);
  await click('id_navbar_loginout');
  await debugSnapshot(fileNamePrefix, snapshots);

  await setFormInput('username_or_email', username);
  await setFormInput('password', password);
  await debugSnapshot(fileNamePrefix, snapshots);

  await click('submit');
  await debugSnapshot(fileNamePrefix, snapshots);
}

async function logout(
  fileNamePrefix = '', snapshots = null, startIndex = null,
) {
  await debugSnapshot(fileNamePrefix, snapshots, startIndex);
  // First check it we can log out
  const button = await page.$('#id_navbar_loginout');
  const className = await ((await button.getProperty('className')).jsonValue());
  if (className !== 'dropdown_button_container') {
    return;
  }
  await Promise.all([
    page.waitForSelector('#id_navbar_loginout_list'),
    page.click('#id_navbar_loginout'),
  ]);
  await debugSnapshot(fileNamePrefix, snapshots);
  const hints = await page.$$('.dropdown_button_list_item_link');
  await debugSnapshot(fileNamePrefix, snapshots);
  await Promise.all([
    page.waitForNavigation(),
    hints[1].click(),
  ]);
  await debugSnapshot(fileNamePrefix, snapshots);
}


async function gotoAccountSettings(
  fileNamePrefix = '', snapshots = null, startIndex = null,
) {
  await debugSnapshot(fileNamePrefix, snapshots, startIndex);
  await Promise.all([
    page.waitForSelector('#id_navbar_loginout_list'),
    page.click('#id_navbar_loginout'),
  ]);
  await debugSnapshot(fileNamePrefix, snapshots);

  const hints = await page.$$('.dropdown_button_list_item_link');
  await Promise.all([
    page.waitForNavigation(),
    hints[0].click(),
  ]);
  await debugSnapshot(fileNamePrefix, snapshots);
}


async function createAccountWithoutConfirm(
  username, email, password,
  fileNamePrefix = '', snapshots = null, startIndex = null,
) {
  await debugSnapshot(fileNamePrefix, snapshots, startIndex);
  await logout();
  await debugSnapshot(fileNamePrefix, snapshots);

  await click('id_navbar_loginout');
  await debugSnapshot(fileNamePrefix, snapshots);

  await click('login_form__create_account');
  await debugSnapshot(fileNamePrefix, snapshots);

  await setFormInput('username', username);
  await setFormInput('email', email);
  await setFormInput('password', password);
  await setFormInput('repeat_password', password);
  await page.$eval('#terms', elem => elem.click());
  await debugSnapshot(fileNamePrefix, snapshots);

  const currentMsgNumber = await getLatestMessage();
  await click('submit');
  await debugSnapshot(fileNamePrefix, snapshots);

  const token = await getToken('confirmAccount', currentMsgNumber);
  return token;
}

async function confirmCreateAccount(token, fileNamePrefix = '', snapshots = null) {
  await page.goto(`${sitePath}/${token}`);
  await debugSnapshot(fileNamePrefix, snapshots);
}


async function createAccount(
  username, email, password,
  fileNamePrefix = '', snapshots = null, startIndex = null,
) {
  // await debugSnapshot(fileNamePrefix, snapshots, startIndex);
  // await logout();
  // await debugSnapshot(fileNamePrefix, snapshots);

  // await click('id_navbar_loginout');
  // await debugSnapshot(fileNamePrefix, snapshots);

  // await click('login_form__create_account');
  // await debugSnapshot(fileNamePrefix, snapshots);

  // await setFormInput('username', username);
  // await setFormInput('email', email);
  // await setFormInput('password', password);
  // await setFormInput('repeat_password', password);
  // await page.$eval('#terms', elem => elem.click());
  // await debugSnapshot(fileNamePrefix, snapshots);

  // const currentMsgNumber = await getLatestMessage();
  // await click('submit');
  // await debugSnapshot(fileNamePrefix, snapshots);

  // const token = await getToken('confirmAccount', currentMsgNumber);
  // await page.goto(`${sitePath}/${token}`);
  // await debugSnapshot(fileNamePrefix, snapshots);
  const token = await createAccountWithoutConfirm(
    username, email, password, fileNamePrefix, snapshots, startIndex,
  );
  await confirmCreateAccount(token, fileNamePrefix, snapshots);
}


async function deleteAccount(username, password, debug) {
  await debugSnapshot(debug, 0);
  await logout();
  await debugSnapshot(debug, 1);

  await login(username, password);
  await debugSnapshot(debug, 2);

  await gotoAccountSettings();
  await debugSnapshot(debug, 3);

  await click('delete_form-submit');
  await debugSnapshot(debug, 4);

  await click('form-submit_delete');
  await debugSnapshot(debug, 5);
}

async function deleteAccountIfExists(username, password, debug) {
  await logout();
  await login(username, password);
  const url = await page.url();
  console.log(url)
  if (url.slice(-5) === 'login') {
    await goHome();
    return;
  }
  await gotoAccountSettings();
  await click('delete_form-submit');
  await click('form-submit_delete');
  await goHome();
}

function cleanReplacementFolder(callingScriptPath) {
  const deleteFolderRecursive = (folderPath) => {
    if (fs.existsSync(folderPath)) {
      fs.readdirSync(folderPath).forEach((file) => {
        const curPath = path.join(folderPath, file);
        if (fs.lstatSync(curPath).isDirectory()) { // recurse
          deleteFolderRecursive(curPath);
        } else { // delete file
          fs.unlinkSync(curPath);
        }
      });
      fs.rmdirSync(folderPath);
    }
  };
  const folder = `${path.join(callingScriptPath, '__image_snapshots__', '__replacements__')}`;
  deleteFolderRecursive(folder);
  return folder;
}

function getReplacementsFolder(callingScriptPath) {
  return `${path.join(callingScriptPath, '__image_snapshots__', '__replacements__')}`;
}

function writeSS(callingScriptPath, fileName, screenshot) {
  const folder = `${path.join(callingScriptPath, '__image_snapshots__', '__replacements__')}`;
  if (!fs.existsSync(folder)) {
    fs.mkdirSync(folder);
  }
  fs.writeFileSync(path.join(folder, `${fileName}-snap.png`), screenshot, () => {});
}

function writeReplacements(callingScriptPath, replacements) {
  // cleanReplacementFolder(callingScriptPath);
  replacements.forEach((ss) => {
    writeSS(__dirname, ...ss);
  });
}

module.exports = {
  deleteAccountIfExists,
  cleanReplacementFolder,
  getReplacementsFolder,
  login,
  gotoAccountSettings,
  snapshot,
  logout,
  sleep,
  getToken,
  getLatestMessage,
  setFormInput,
  click,
  goHome,
  createAccount,
  createAccountWithoutConfirm,
  confirmCreateAccount,
  deleteAccount,
  snap,
  writeReplacements,
  checkSnap,
};
