# Production SIMILAR environment with differences:
#  - App files are mounted in a volume to the container instead of being copied 
#    into the container
#  - Flask is run instead of gunicorn so flask errors can be seen
# 
# Is build on python base image (instead of nodepy like in dev) 

FROM python:3.7.3-slim

WORKDIR /opt/app

# This is the folder that will be shared with the docker host machine
RUN mkdir app
RUN mkdir tests

ADD requirements.txt .
RUN pip install --no-cache-dir -q -r requirements.txt





ENV FLASK_APP app/my_app.py



RUN useradd -m myuser
USER myuser


ENTRYPOINT ["flask", "run", "--host=0.0.0.0"]
# ENTRYPOINT ["bash"]