# Production environment that can be used directly on Heroku. 
# Differences to stage include:
#  - App files are copied into the container, no volume mounting
#  - Gunicorn is run directly



FROM python:3.6.6-slim

WORKDIR /opt/app





ADD containers/shared/requirements_prod.txt requirements.txt

RUN pip install --no-cache-dir -q -r requirements.txt

ADD containers/prod/Procfile .
ADD containers/prod/runtime.txt .
ADD containers/prod/wsgi.py .
ADD app/. .
# RUN rm -rf /opt/app/app/static/src




RUN useradd -m myuser
USER myuser





CMD gunicorn --bind 0.0.0.0:$PORT wsgi
