# Production environment that can be used directly on Heroku. 
# Differences to stage include:
#  - App files are copied into the container, no volume mounting
#  - Gunicorn is run directly



FROM python:3.7.2-slim

WORKDIR /opt/app


ADD requirements.txt .
RUN pip install --no-cache-dir -q -r requirements.txt


ADD containers/prod/Procfile .
ADD containers/prod/runtime.txt .
ADD containers/prod/wsgi.py .
ADD app/. .
# RUN rm -rf /opt/app/app/static/src




RUN useradd -m myuser
RUN chown myuser app
RUN chown myuser app/app.db
RUN chmod 666 app/app.db
USER myuser

ARG mail_password
ARG database_url
ENV MAIL_PASSWORD=$mail_password
ENV DATABASE_URL=$database_url



CMD gunicorn --bind 0.0.0.0:$PORT wsgi
