"""empty message

Revision ID: 0378b3679dbc
Revises: 429a68310eed
Create Date: 2019-06-05 17:22:35.333747

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0378b3679dbc'
down_revision = '429a68310eed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('versions', sa.Column('htmlDescription', sa.String(length=256), nullable=True))
    op.add_column('versions', sa.Column('htmlTitle', sa.String(length=128), nullable=True))
    op.create_index(op.f('ix_versions_htmlDescription'), 'versions', ['htmlDescription'], unique=True)
    op.create_index(op.f('ix_versions_htmlTitle'), 'versions', ['htmlTitle'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_versions_htmlTitle'), table_name='versions')
    op.drop_index(op.f('ix_versions_htmlDescription'), table_name='versions')
    op.drop_column('versions', 'htmlTitle')
    op.drop_column('versions', 'htmlDescription')
    # ### end Alembic commands ###
