"""empty message

Revision ID: 1b99897c4ef5
Revises: af1fdaf13396
Create Date: 2019-05-21 06:47:00.299987

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b99897c4ef5'
down_revision = 'af1fdaf13396'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('links', sa.Column('url_hash', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('links', 'url_hash')
    # ### end Alembic commands ###
