"""empty message

Revision ID: 41d5acffae2d
Revises: 611356a5f5c0
Create Date: 2019-02-01 10:34:54.638818

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41d5acffae2d'
down_revision = '611356a5f5c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email_hash', sa.Binary(), nullable=True))
    op.drop_index('ix_users_encrypted_email', table_name='users')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_users_encrypted_email', 'users', ['encrypted_email'], unique=1)
    op.drop_column('users', 'email_hash')
    # ### end Alembic commands ###
