"""empty message

Revision ID: 44d4be67cb02
Revises: d1edd946dca9
Create Date: 2019-08-13 15:20:35.676685

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44d4be67cb02'
down_revision = 'd1edd946dca9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('username_hash', sa.String(length=31), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'username_hash')
    # ### end Alembic commands ###
