"""empty message

Revision ID: 4b724ee66217
Revises: 77d08d166367
Create Date: 2019-09-13 16:45:50.520026

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b724ee66217'
down_revision = '77d08d166367'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('link_ratings_cache', sa.Column('link_hash', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('link_ratings_cache', 'link_hash')
    # ### end Alembic commands ###
