"""empty message

Revision ID: 4f30351bb3b9
Revises: 5ca447de807a
Create Date: 2019-01-22 11:27:58.481580

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f30351bb3b9'
down_revision = '5ca447de807a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lesson',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lesson_name', sa.String(length=128), nullable=True),
    sa.Column('lesson_uid', sa.String(length=128), nullable=True),
    sa.Column('category', sa.Integer(), nullable=True),
    sa.Column('dependencies', sa.String(length=1024), nullable=True),
    sa.Column('path', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['category'], ['category.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lesson_dependencies'), 'lesson', ['dependencies'], unique=False)
    op.create_index(op.f('ix_lesson_lesson_name'), 'lesson', ['lesson_name'], unique=True)
    op.create_index(op.f('ix_lesson_lesson_uid'), 'lesson', ['lesson_uid'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_lesson_lesson_uid'), table_name='lesson')
    op.drop_index(op.f('ix_lesson_lesson_name'), table_name='lesson')
    op.drop_index(op.f('ix_lesson_dependencies'), table_name='lesson')
    op.drop_table('lesson')
    # ### end Alembic commands ###
