"""empty message

Revision ID: 6c54fb3ed018
Revises: 4b724ee66217
Create Date: 2020-03-31 15:50:02.815916

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c54fb3ed018'
down_revision = '4b724ee66217'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('new_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=88), nullable=True),
    sa.Column('username_hash', sa.String(length=31), nullable=True),
    sa.Column('email', sa.String(length=472), nullable=True),
    sa.Column('email_hash', sa.String(length=31), nullable=True),
    sa.Column('password', sa.String(length=124), nullable=True),
    sa.Column('signed_up_on', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_new_users_username'), 'new_users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_new_users_username'), table_name='new_users')
    op.drop_table('new_users')
    # ### end Alembic commands ###
