"""empty message

Revision ID: 73384acda10d
Revises: 9673eec9751e
Create Date: 2019-01-22 12:27:40.122375

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73384acda10d'
down_revision = '9673eec9751e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'salt')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('salt', sa.VARCHAR(length=128), nullable=True))
    # ### end Alembic commands ###
