"""empty message

Revision ID: 77d08d166367
Revises: 
Create Date: 2019-09-13 16:30:50.731578

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77d08d166367'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('link_ratings_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version_uid', sa.String(length=256), nullable=True),
    sa.Column('num_ratings', sa.Integer(), nullable=True),
    sa.Column('ave_rating', sa.Float(), nullable=True),
    sa.Column('high_ratings', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_link_ratings_cache_ave_rating'), 'link_ratings_cache', ['ave_rating'], unique=False)
    op.create_index(op.f('ix_link_ratings_cache_high_ratings'), 'link_ratings_cache', ['high_ratings'], unique=False)
    op.create_index(op.f('ix_link_ratings_cache_num_ratings'), 'link_ratings_cache', ['num_ratings'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=88), nullable=True),
    sa.Column('username_hash', sa.String(length=31), nullable=True),
    sa.Column('email', sa.String(length=472), nullable=True),
    sa.Column('email_hash', sa.String(length=31), nullable=True),
    sa.Column('password', sa.String(length=124), nullable=True),
    sa.Column('signed_up_on', sa.DateTime(), nullable=True),
    sa.Column('confirmed', sa.Boolean(), nullable=True),
    sa.Column('confirmed_on', sa.DateTime(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('version_ratings_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('topic_uid', sa.String(length=256), nullable=True),
    sa.Column('approach_version', sa.String(length=256), nullable=True),
    sa.Column('num_ratings', sa.Integer(), nullable=True),
    sa.Column('ave_rating', sa.Float(), nullable=True),
    sa.Column('high_ratings', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_version_ratings_cache_ave_rating'), 'version_ratings_cache', ['ave_rating'], unique=False)
    op.create_index(op.f('ix_version_ratings_cache_high_ratings'), 'version_ratings_cache', ['high_ratings'], unique=False)
    op.create_index(op.f('ix_version_ratings_cache_num_ratings'), 'version_ratings_cache', ['num_ratings'], unique=False)
    op.create_table('link_ratings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('version_uid', sa.String(length=256), nullable=True),
    sa.Column('link_hash', sa.String(length=32), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_link_ratings_rating'), 'link_ratings', ['rating'], unique=False)
    op.create_index(op.f('ix_link_ratings_timestamp'), 'link_ratings', ['timestamp'], unique=False)
    op.create_table('version_ratings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('version_uid', sa.String(length=256), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_version_ratings_rating'), 'version_ratings', ['rating'], unique=False)
    op.create_index(op.f('ix_version_ratings_timestamp'), 'version_ratings', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_version_ratings_timestamp'), table_name='version_ratings')
    op.drop_index(op.f('ix_version_ratings_rating'), table_name='version_ratings')
    op.drop_table('version_ratings')
    op.drop_index(op.f('ix_link_ratings_timestamp'), table_name='link_ratings')
    op.drop_index(op.f('ix_link_ratings_rating'), table_name='link_ratings')
    op.drop_table('link_ratings')
    op.drop_index(op.f('ix_version_ratings_cache_num_ratings'), table_name='version_ratings_cache')
    op.drop_index(op.f('ix_version_ratings_cache_high_ratings'), table_name='version_ratings_cache')
    op.drop_index(op.f('ix_version_ratings_cache_ave_rating'), table_name='version_ratings_cache')
    op.drop_table('version_ratings_cache')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_link_ratings_cache_num_ratings'), table_name='link_ratings_cache')
    op.drop_index(op.f('ix_link_ratings_cache_high_ratings'), table_name='link_ratings_cache')
    op.drop_index(op.f('ix_link_ratings_cache_ave_rating'), table_name='link_ratings_cache')
    op.drop_table('link_ratings_cache')
    # ### end Alembic commands ###
