"""empty message

Revision ID: afa09761b680
Revises: 
Create Date: 2019-05-15 14:06:03.008241

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'afa09761b680'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=True),
    sa.Column('path', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_categories_category'), 'categories', ['category'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=32), nullable=True),
    sa.Column('email', sa.String(length=472), nullable=True),
    sa.Column('email_hash', sa.String(length=31), nullable=True),
    sa.Column('password', sa.String(length=124), nullable=True),
    sa.Column('signed_up_on', sa.DateTime(), nullable=True),
    sa.Column('confirmed', sa.Boolean(), nullable=True),
    sa.Column('confirmed_on', sa.DateTime(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('lessons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=True),
    sa.Column('uid', sa.String(length=128), nullable=True),
    sa.Column('category', sa.Integer(), nullable=True),
    sa.Column('dependencies', sa.String(length=1024), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('path', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['category'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lessons_dependencies'), 'lessons', ['dependencies'], unique=False)
    op.create_index(op.f('ix_lessons_enabled'), 'lessons', ['enabled'], unique=False)
    op.create_index(op.f('ix_lessons_title'), 'lessons', ['title'], unique=True)
    op.create_index(op.f('ix_lessons_uid'), 'lessons', ['uid'], unique=True)
    op.create_table('topics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('lesson_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_topics_name'), 'topics', ['name'], unique=False)
    op.create_table('versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=True),
    sa.Column('uid', sa.String(length=128), nullable=True),
    sa.Column('title', sa.String(length=128), nullable=True),
    sa.Column('description', sa.String(length=256), nullable=True),
    sa.Column('fullLesson', sa.Boolean(), nullable=True),
    sa.Column('pageType', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_versions_description'), 'versions', ['description'], unique=False)
    op.create_index(op.f('ix_versions_fullLesson'), 'versions', ['fullLesson'], unique=False)
    op.create_index(op.f('ix_versions_pageType'), 'versions', ['pageType'], unique=False)
    op.create_index(op.f('ix_versions_title'), 'versions', ['title'], unique=False)
    op.create_index(op.f('ix_versions_uid'), 'versions', ['uid'], unique=False)
    op.create_table('all_ratings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('version_id', sa.Integer(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('page', sa.Integer(), nullable=True),
    sa.Column('pages', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['version_id'], ['versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_all_ratings_rating'), 'all_ratings', ['rating'], unique=False)
    op.create_index(op.f('ix_all_ratings_timestamp'), 'all_ratings', ['timestamp'], unique=False)
    op.create_table('ratings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('version_id', sa.Integer(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['version_id'], ['versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ratings_rating'), 'ratings', ['rating'], unique=False)
    op.create_table('comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rating_id', sa.Integer(), nullable=True),
    sa.Column('comment', sa.String(length=2048), nullable=True),
    sa.ForeignKeyConstraint(['rating_id'], ['ratings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comment')
    op.drop_index(op.f('ix_ratings_rating'), table_name='ratings')
    op.drop_table('ratings')
    op.drop_index(op.f('ix_all_ratings_timestamp'), table_name='all_ratings')
    op.drop_index(op.f('ix_all_ratings_rating'), table_name='all_ratings')
    op.drop_table('all_ratings')
    op.drop_index(op.f('ix_versions_uid'), table_name='versions')
    op.drop_index(op.f('ix_versions_title'), table_name='versions')
    op.drop_index(op.f('ix_versions_pageType'), table_name='versions')
    op.drop_index(op.f('ix_versions_fullLesson'), table_name='versions')
    op.drop_index(op.f('ix_versions_description'), table_name='versions')
    op.drop_table('versions')
    op.drop_index(op.f('ix_topics_name'), table_name='topics')
    op.drop_table('topics')
    op.drop_index(op.f('ix_lessons_uid'), table_name='lessons')
    op.drop_index(op.f('ix_lessons_title'), table_name='lessons')
    op.drop_index(op.f('ix_lessons_enabled'), table_name='lessons')
    op.drop_index(op.f('ix_lessons_dependencies'), table_name='lessons')
    op.drop_table('lessons')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_categories_category'), table_name='categories')
    op.drop_table('categories')
    # ### end Alembic commands ###
