"""empty message

Revision ID: c9d3de4a63f8
Revises: e1816261267b
Create Date: 2019-05-19 21:17:56.132964

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9d3de4a63f8'
down_revision = 'e1816261267b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('links', sa.Column('publisher', sa.String(length=128), nullable=True))
    op.create_index(op.f('ix_links_publisher'), 'links', ['publisher'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_links_publisher'), table_name='links')
    op.drop_column('links', 'publisher')
    # ### end Alembic commands ###
