"""empty message

Revision ID: d1edd946dca9
Revises: 0378b3679dbc
Create Date: 2019-06-05 17:47:50.747095

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1edd946dca9'
down_revision = '0378b3679dbc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_versions_htmlDescription', table_name='versions')
    op.create_index(op.f('ix_versions_htmlDescription'), 'versions', ['htmlDescription'], unique=False)
    op.drop_index('ix_versions_htmlTitle', table_name='versions')
    op.create_index(op.f('ix_versions_htmlTitle'), 'versions', ['htmlTitle'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_versions_htmlTitle'), table_name='versions')
    op.create_index('ix_versions_htmlTitle', 'versions', ['htmlTitle'], unique=1)
    op.drop_index(op.f('ix_versions_htmlDescription'), table_name='versions')
    op.create_index('ix_versions_htmlDescription', 'versions', ['htmlDescription'], unique=1)
    # ### end Alembic commands ###
