"""empty message

Revision ID: e1816261267b
Revises: 4bd778094d61
Create Date: 2019-05-19 21:12:59.545960

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1816261267b'
down_revision = '4bd778094d61'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('path', sa.String(length=512), nullable=True),
    sa.Column('author', sa.String(length=128), nullable=True),
    sa.Column('pageType', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_links_author'), 'links', ['author'], unique=False)
    op.create_index(op.f('ix_links_pageType'), 'links', ['pageType'], unique=False)
    op.create_index(op.f('ix_links_path'), 'links', ['path'], unique=False)
    op.create_table('link_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=True),
    sa.Column('link_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['link_id'], ['links.id'], ),
    sa.ForeignKeyConstraint(['version_id'], ['versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('all_link_ratings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('link_version_id', sa.Integer(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['link_version_id'], ['link_versions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_all_link_ratings_rating'), 'all_link_ratings', ['rating'], unique=False)
    op.create_index(op.f('ix_all_link_ratings_timestamp'), 'all_link_ratings', ['timestamp'], unique=False)
    op.create_table('link_ratings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('link_version_id', sa.Integer(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['link_version_id'], ['link_versions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_link_ratings_rating'), 'link_ratings', ['rating'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_link_ratings_rating'), table_name='link_ratings')
    op.drop_table('link_ratings')
    op.drop_index(op.f('ix_all_link_ratings_timestamp'), table_name='all_link_ratings')
    op.drop_index(op.f('ix_all_link_ratings_rating'), table_name='all_link_ratings')
    op.drop_table('all_link_ratings')
    op.drop_table('link_versions')
    op.drop_index(op.f('ix_links_path'), table_name='links')
    op.drop_index(op.f('ix_links_pageType'), table_name='links')
    op.drop_index(op.f('ix_links_author'), table_name='links')
    op.drop_table('links')
    # ### end Alembic commands ###
